// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3z5a-u4a_XS0pq1vDKlqAFxODqHYQCuM',
    appId: '1:114661168141:web:be482bf3c53819e0057144',
    messagingSenderId: '114661168141',
    projectId: 'blogapp-ba67f',
    authDomain: 'blogapp-ba67f.firebaseapp.com',
    storageBucket: 'blogapp-ba67f.firebasestorage.app',
    measurementId: 'G-4WGDNRHFHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkAS2iVXLAJfxlYLIRui-8cJuZXQ9MnQg',
    appId: '1:114661168141:android:e7fd7b82c2b32ffd057144',
    messagingSenderId: '114661168141',
    projectId: 'blogapp-ba67f',
    storageBucket: 'blogapp-ba67f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUUz4pAbsRXWUngwSW3hMr7WmYtNKRC9k',
    appId: '1:114661168141:ios:652be851d3ca9dc7057144',
    messagingSenderId: '114661168141',
    projectId: 'blogapp-ba67f',
    storageBucket: 'blogapp-ba67f.firebasestorage.app',
    iosBundleId: 'com.example.uasapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUUz4pAbsRXWUngwSW3hMr7WmYtNKRC9k',
    appId: '1:114661168141:ios:652be851d3ca9dc7057144',
    messagingSenderId: '114661168141',
    projectId: 'blogapp-ba67f',
    storageBucket: 'blogapp-ba67f.firebasestorage.app',
    iosBundleId: 'com.example.uasapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3z5a-u4a_XS0pq1vDKlqAFxODqHYQCuM',
    appId: '1:114661168141:web:802ddf5161375b7a057144',
    messagingSenderId: '114661168141',
    projectId: 'blogapp-ba67f',
    authDomain: 'blogapp-ba67f.firebaseapp.com',
    storageBucket: 'blogapp-ba67f.firebasestorage.app',
    measurementId: 'G-NKQJX0ZLE7',
  );
}
